# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-21 12:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='city',
            new_name='phone_number',
        ),
    ]
