# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-27 11:40
from __future__ import unicode_literals

from django.db import migrations, models
import planome.models


class Migration(migrations.Migration):

    dependencies = [
        ('planome', '0003_auto_20190627_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to=planome.models.image_path),
        ),
    ]
