# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-27 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planome', '0002_auto_20190627_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='image/products/<function __str__ at 0x7f695e6c1320>/<function __str__ at 0x7f695e6c1320>'),
        ),
    ]
